<a href="https://colab.research.google.com/github/VrishankDesaiSLRTCE/Compozent/blob/Regression-Model-ML/ML_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [6]:
df = pd.read_excel('/content/tested (1).xlsx')
df[100:110]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,992,1,1,"Stengel, Mrs. Charles Emil Henry (Annie May Mo...",female,43.0,1,0,11778,55.4417,C116,C
101,993,0,2,"Weisz, Mr. Leopold",male,27.0,1,0,228414,26.0000,NaN,S
102,994,0,3,"Foley, Mr. William",male,NaN,0,0,365235,7.7500,NaN,Q
103,995,0,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.0,0,0,347070,7.7750,NaN,S
104,996,1,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.0,1,1,2625,8.5167,NaN,C
105,997,0,3,"Holthen, Mr. Johan Martin",male,28.0,0,0,C 4001,22.5250,NaN,S
106,998,0,3,"Buckley, Mr. Daniel",male,21.0,0,0,330920,7.8208,NaN,Q
107,999,0,3,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.7500,NaN,Q
108,1000,0,3,"Willer, Mr. Aaron (Abi Weller"")""",male,NaN,0,0,3410,8.7125,NaN,S
109,1001,0,2,"Swane, Mr. George",male,18.5,0,0,248734,13.0000,F,S

In [7]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]>

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
len(df)

418

In [10]:
df.drop(columns=['PassengerId','Name','Ticket'],inplace=True)

In [11]:
df.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  34.5      0      0   7.8292   NaN        Q
1         1       3  female  47.0      1      0   7.0000   NaN        S
2         0       2    male  62.0      0      0   9.6875   NaN        Q
3         0       3    male  27.0      0      0   8.6625   NaN        S
4         1       3  female  22.0      1      1  12.2875   NaN        S

In [12]:
df['Survived'].unique()

array([0, 1])

In [13]:
d = {"Pclass":"Tier", "Sex":"Gender", "SibSp":"Number of Siblings/Spouses Aboard","Parch":"Number of Parents/Children Aboard"}
df.rename(columns=d, inplace=True)

In [14]:
df.head(5)

,Survived,Tier,Gender,Age,Number of Siblings/Spouses Aboard,Number of Parents/Children Aboard,Fare,Cabin,Embarked
0,0,3,male,34.5,0,0,7.8292,NaN,Q
1,1,3,female,47.0,1,0,7.0000,NaN,S
2,0,2,male,62.0,0,0,9.6875,NaN,Q
3,0,3,male,27.0,0,0,8.6625,NaN,S
4,1,3,female,22.0,1,1,12.2875,NaN,S

In [15]:
df.isna().sum()

Survived                               0
Tier                                   0
Gender                                 0
Age                                   86
Number of Siblings/Spouses Aboard      0
Number of Parents/Children Aboard      0
Fare                                   1
Cabin                                327
Embarked                               0
dtype: int64

In [16]:
df.dropna(subset=["Age"])

,Survived,Tier,Gender,Age,Number of Siblings/Spouses Aboard,Number of Parents/Children Aboard,Fare,Cabin,Embarked
0,0,3,male,34.5,0,0,7.8292,NaN,Q
1,1,3,female,47.0,1,0,7.0000,NaN,S
2,0,2,male,62.0,0,0,9.6875,NaN,Q
3,0,3,male,27.0,0,0,8.6625,NaN,S
4,1,3,female,22.0,1,1,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...
409,1,3,female,3.0,1,1,13.7750,NaN,S
411,1,1,female,37.0,1,0,90.0000,C78,Q
412,1,3,female,28.0,0,0,7.7750,NaN,S
414,1,1,female,39.0,0,0,108.9000,C105,C
415,0,3,male,38.5,0,0,7.2500,NaN,S

In [17]:
df['Age'].fillna(df['Age'].median(),inplace=True)
df['Cabin'].fillna('General Cabin',inplace=True)
df['Fare'].fillna(df['Fare'].median(),inplace=True)

<ipython-input-17-fd703e0b19cf>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)
<ipython-input-17-fd703e0b19cf>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna('General Cabin',inplace=True)
<ipython-input-17-fd703e0b19cf>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].median(),inplace=True)

In [18]:
df.head(5)

,Survived,Tier,Gender,Age,Number of Siblings/Spouses Aboard,Number of Parents/Children Aboard,Fare,Cabin,Embarked
0,0,3,male,34.5,0,0,7.8292,General Cabin,Q
1,1,3,female,47.0,1,0,7.0000,General Cabin,S
2,0,2,male,62.0,0,0,9.6875,General Cabin,Q
3,0,3,male,27.0,0,0,8.6625,General Cabin,S
4,1,3,female,22.0,1,1,12.2875,General Cabin,S

In [19]:
df.isna().sum()

Survived                             0
Tier                                 0
Gender                               0
Age                                  0
Number of Siblings/Spouses Aboard    0
Number of Parents/Children Aboard    0
Fare                                 0
Cabin                                0
Embarked                             0
dtype: int64

In [20]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender']) #male 0, female 1
df['Cabin'] = le.fit_transform(df['Cabin']) #general cabin 76
df['Embarked'] = le.fit_transform(df['Embarked']) #Q -1 , S-2, C-0
df.head()

,Survived,Tier,Gender,Age,Number of Siblings/Spouses Aboard,Number of Parents/Children Aboard,Fare,Cabin,Embarked
0,0,3,1,34.5,0,0,7.8292,76,1
1,1,3,0,47.0,1,0,7.0000,76,2
2,0,2,1,62.0,0,0,9.6875,76,1
3,0,3,1,27.0,0,0,8.6625,76,2
4,1,3,0,22.0,1,1,12.2875,76,2

In [21]:
ss = StandardScaler()
df[['Age','Fare']] = ss.fit_transform(df[['Age','Fare']])
df.head(10)

,Survived,Tier,Gender,Age,Number of Siblings/Spouses Aboard,Number of Parents/Children Aboard,Fare,Cabin,Embarked
0,0,3,1,0.386231,0,0,-0.497413,76,1
1,1,3,0,1.371370,1,0,-0.512278,76,2
2,0,2,1,2.553537,0,0,-0.464100,76,1
3,0,3,1,-0.204852,0,0,-0.482475,76,2
4,1,3,0,-0.598908,1,1,-0.417492,76,2
5,0,3,1,-1.229397,0,0,-0.472391,76,2
6,1,3,0,0.031581,0,0,-0.500999,76,1
7,0,2,1,-0.283663,1,1,-0.117894,76,2
8,1,3,0,-0.914152,0,0,-0.508169,76,0
9,0,3,1,-0.677719,2,0,-0.204838,76,2

In [22]:
X = df[['Tier','Gender','Age','Number of Siblings/Spouses Aboard','Number of Parents/Children Aboard','Fare','Cabin','Embarked']]#feature
y = df['Survived']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [24]:
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [25]:
y_pred = model.predict(X_test)
print(y_pred)

[1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0 1 1 0 0 1
 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0
 1 0 0 0 1 0 0 1 1 0]

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [27]:
print(accuracy_score(y_test,y_pred))

1.0

In [28]:
print(confusion_matrix(y_test,y_pred))

[[49  0]
 [ 0 35]]

In [29]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [30]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train,y_train)

RandomForestClassifier()

In [31]:
with open('titanic.pkl','wb') as f:
    pickle.dump(model,f)